# Generated by Django 5.2.5 on 2025-08-31 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_km', models.FloatField()),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=20)),
                ('electricity_kwh', models.FloatField()),
                ('renewable_energy', models.BooleanField(default=False)),
                ('food_meat', models.FloatField()),
                ('food_dairy', models.FloatField()),
                ('food_plant', models.FloatField()),
                ('waste_kg', models.FloatField()),
                ('recycling_score', models.FloatField()),
                ('water_liters', models.FloatField()),
                ('shopping_spend', models.FloatField()),
                ('prediction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
